"""Email automation for invalid audits.

Only **Invalid** audits trigger an automatic email (configurable). Recipients
are the agent's Team Leader and Operations Manager plus the QA distribution
list configured in the Admin Center. When online the message is sent through
Microsoft Graph ``/me/sendMail``; when offline (or sending fails) a portable
``.eml`` file is written to the backups folder so nothing is lost and the
message can be sent manually.
"""

from __future__ import annotations

from email.message import EmailMessage
from pathlib import Path

import requests

from .. import config
from ..auth.session import SessionManager, get_session
from ..core.logging_config import get_logger
from ..core.models import Audit
from ..core.utils import is_valid_email, now_iso, split_recipients
from ..data.logs_store import LogsRepository
from ..data.settings_store import SettingsStore

_log = get_logger(__name__)


class EmailService:
    """Compose and dispatch invalid-audit notification emails."""

    def __init__(
        self,
        *,
        settings: SettingsStore | None = None,
        logs: LogsRepository | None = None,
        session: SessionManager | None = None,
    ):
        self.settings = settings or SettingsStore()
        self.logs = logs or LogsRepository()
        self.session = session or get_session()

    # -- recipients ---------------------------------------------------------

    def resolve_recipients(self, audit: Audit) -> list[str]:
        """Return the de-duplicated recipient list for an audit's email."""
        recipients: list[str] = []
        # The agent, their TL and their OM all receive the notification.
        if is_valid_email(audit.agent_email):
            recipients.append(audit.agent_email.strip())
        if is_valid_email(audit.tl_email):
            recipients.append(audit.tl_email.strip())
        if is_valid_email(audit.om_email):
            recipients.append(audit.om_email.strip())

        # QA distribution list (free-text setting).
        recipients += split_recipients(
            self.settings.get("email.qa_distribution_list", "")
        )
        # Structured recipient table (Name/Email/Role).
        for entry in self.settings.get_recipients():
            email = entry.get("Email", "").strip()
            if is_valid_email(email):
                recipients.append(email)

        # De-duplicate, preserve order.
        seen: set[str] = set()
        unique: list[str] = []
        for r in recipients:
            key = r.lower()
            if key not in seen:
                seen.add(key)
                unique.append(r)
        return unique

    # -- message construction ----------------------------------------------

    def build_subject(self, audit: Audit) -> str:
        template = self.settings.get(
            "email.subject_template", "[EQMS] Invalid Audit {audit_id} - {agent}"
        )
        try:
            return template.format(audit_id=audit.audit_id, agent=audit.agent,
                                   eid=audit.agent_eid)
        except (KeyError, IndexError):
            return f"[EQMS] Invalid Audit {audit.audit_id} - {audit.agent}"

    def build_body_html(self, audit: Audit) -> str:
        """Render the audit detail email body as simple, email-safe HTML."""
        org = self.settings.get("app.organisation", "HP Mainstream Quality Assurance")
        color = self.settings.get("app.primary_color", "#0F4C81")
        rows = [
            ("Audit ID", audit.audit_id),
            ("Date", audit.date),
            ("QA", audit.qa_name),
            ("Auditor", audit.auditor_name),
            ("Agent", audit.agent),
            ("Agent EID", audit.agent_eid),
            ("Agent Email", audit.agent_email),
            ("Region", audit.region),
            ("Team Leader", audit.team_leader),
            ("Operations Manager", audit.operations_manager),
            ("Case Number", audit.case_number),
            ("Genesys Transaction ID", audit.genesys_id),
            ("Validation", audit.validation),
            ("Reason", audit.reason),
            ("Remarks", audit.remarks),
        ]
        cells = "".join(
            f"<tr><td style='padding:6px 12px;border:1px solid #ddd;"
            f"background:#f4f7fb;font-weight:bold'>{label}</td>"
            f"<td style='padding:6px 12px;border:1px solid #ddd'>{_esc(value)}</td></tr>"
            for label, value in rows
        )
        return f"""\
<html><body style="font-family:Segoe UI,Arial,sans-serif;color:#222">
  <h2 style="color:{color};margin-bottom:4px">Invalid Audit Notification</h2>
  <p style="color:#555;margin-top:0">{org}</p>
  <table style="border-collapse:collapse;font-size:14px">{cells}</table>
  <p style="color:#888;font-size:12px;margin-top:18px">
    This is an automated notification generated by {config.APP_SHORT_NAME}.
  </p>
</body></html>"""

    # -- sending ------------------------------------------------------------

    def should_send(self, audit: Audit) -> bool:
        if not self.settings.get_bool("email.enabled", True):
            return False
        if self.settings.get_bool("email.send_on_invalid_only", True):
            return audit.is_invalid
        return True

    def send_audit_email(self, audit: Audit) -> tuple[bool, str]:
        """Send (or queue) the notification for an audit.

        Returns ``(sent, detail)`` where ``sent`` indicates whether the message
        was delivered online; if not, ``detail`` points to the saved ``.eml``.
        """
        if not self.should_send(audit):
            return False, "Email not required for this audit"

        recipients = self.resolve_recipients(audit)
        if not recipients:
            _log.warning("No recipients resolved for audit %s", audit.audit_id)
            return False, "No valid recipients configured"

        subject = self.build_subject(audit)
        html = self.build_body_html(audit)

        if self.session.is_online:
            try:
                self._send_via_graph(recipients, subject, html)
                self.logs.record(
                    "EMAIL_SENT", user=self.session.user.email,
                    details=f"{audit.audit_id} -> {', '.join(recipients)}",
                )
                return True, "Email sent via Microsoft 365"
            except Exception as exc:  # noqa: BLE001 - fall back to .eml
                _log.error("Graph sendMail failed, saving .eml: %s", exc)

        path = self._save_eml(recipients, subject, html, audit)
        self.logs.record(
            "EMAIL_QUEUED",
            user=self.session.user.email if self.session.is_authenticated else "system",
            details=f"{audit.audit_id} -> {path.name}",
        )
        return False, f"Saved email to {path}"

    def _send_via_graph(self, recipients: list[str], subject: str, html: str) -> None:
        token = self.session.provider.get_token()
        payload = {
            "message": {
                "subject": subject,
                "body": {"contentType": "HTML", "content": html},
                "toRecipients": [
                    {"emailAddress": {"address": r}} for r in recipients
                ],
            },
            "saveToSentItems": True,
        }
        resp = requests.post(
            f"{config.GRAPH_BASE_URL}/me/sendMail",
            headers={"Authorization": f"Bearer {token}",
                     "Content-Type": "application/json"},
            json=payload,
            timeout=30,
        )
        if resp.status_code not in (200, 202):
            raise RuntimeError(f"Graph sendMail returned {resp.status_code}: {resp.text}")

    def _save_eml(self, recipients: list[str], subject: str, html: str,
                  audit: Audit) -> Path:
        config.ensure_directories()
        msg = EmailMessage()
        msg["Subject"] = subject
        msg["From"] = (
            self.session.user.email if self.session.is_authenticated else "eqms@local"
        )
        msg["To"] = ", ".join(recipients)
        msg.set_content("This audit notification requires an HTML-capable client.")
        msg.add_alternative(html, subtype="html")

        out_dir = config.BACKUP_DIR / "outbox"
        out_dir.mkdir(parents=True, exist_ok=True)
        path = out_dir / f"{audit.audit_id}_{now_iso().replace(':', '-')}.eml"
        path.write_bytes(bytes(msg))
        _log.info("Saved audit email to %s", path)
        return path


def _esc(value: str) -> str:
    """Minimal HTML escaping for email cell values."""
    return (
        (value or "")
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )
